apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-08-30T19:04:18Z"
  generation: 2
  labels:
    app: echo-app
  name: echo-app
  namespace: default
  resourceVersion: "2610"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/echo-app
  uid: 382b7bb5-a862-4d4c-a5ca-2e53c62be7b1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echo-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-app
    spec:
      containers:
      - image: gcr.io/qwiklabs-gcp-01-e0a741c9033a/echo-app:v1
        imagePullPolicy: IfNotPresent
        name: echo-app-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-08-30T19:04:21Z"
    lastUpdateTime: "2020-08-30T19:04:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-08-30T19:04:18Z"
    lastUpdateTime: "2020-08-30T19:04:21Z"
    message: ReplicaSet "echo-app-fc565946" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1